# Generated by Django 5.2 on 2025-09-25 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='libro',
            table='Libro',
        ),
    ]
