# Generated by Django 5.2 on 2025-09-27 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_alter_libro_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='ingresar tu nombre', max_length=50)),
                ('apellido', models.CharField(help_text='ingresar tu apellido', max_length=50)),
                ('correo', models.EmailField(blank=True, help_text='engresa tu correo', max_length=254, null=True)),
                ('telefono', models.IntegerField(max_length=30)),
            ],
        ),
    ]
