# Generated by Django 5.2 on 2025-09-27 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0004_genero_alter_cliente_telefono_alter_cliente_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genero',
            name='nombre',
            field=models.CharField(help_text='genero del libro', max_length=50),
        ),
        migrations.AlterField(
            model_name='libro',
            name='autor',
            field=models.CharField(help_text='el autor', max_length=30),
        ),
        migrations.AlterField(
            model_name='libro',
            name='titulo',
            field=models.CharField(help_text='titulo del libro', max_length=30),
        ),
    ]
