# Generated by Django 5.2 on 2025-09-27 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0005_alter_genero_nombre_alter_libro_autor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='imagen',
            field=models.ImageField(null=True, upload_to='libro'),
        ),
    ]
